### ISSUE TITLE
fuel efficiency

### ISSUE THREAD

**Issue by polarisow** [henkelmax/ultimate-plane-mod#1]
Add in the configuration option the ability to change the fuel consumption efficiency (similar to the ultimate car mod) preferably to the latest version of minecraft 1.16.5

**Comment by nouknouk** [comment]
#8

**Comment by Alpaka2k** [comment]
got question is there a file somewhere to change wrench to repair plane faster or plane to get less damage and can i somewhere change plane tank capacity
