### ISSUE TITLE
A way to disable plane damages

### ISSUE THREAD

**Issue by ExDomino** [henkelmax/ultimate-plane-mod#12]
Hello, because it's really too easy to crash, is there a way to disable plane damage please? Thank you in advance.

**Comment by ExDomino** [comment]
How I'm supposed to do that ?
What "property" I have to edit on planes ? "damage" ?
I have to set that to 0 or another maximum value (full life) ?

**Comment by henkelmax** [comment]
Just view the NBT data first. This is pretty self explaining.
