### ISSUE TITLE
[1.16.5] Plane are gone if left-click with a wrench

### ISSUE THREAD

**Issue by ExDomino** [henkelmax/ultimate-plane-mod#13]
**Please read the [FAQ](https://modrepo.de/minecraft/plane/faq) before submitting a bug report!**

**Bug description**

Plane are gone if left click with a wrench.

**Steps to reproduce the issue**
1. Craft and place a plane on the ground.
2. Be sure the plane is not damaged.
3. Left click on it with a wrench.
4. See the plane is gone and not in your inventory.

**Expected behavior**

The wrench should give you the plane in your inventory, or if full, drop it on the ground.
My inventory was not full when I noticed the bug.

**Log files**

There is no log files since there is no crash.

**Versions**
- Minecraft version 1.16.5
- Forge version : 36.2.0
- Ultimate Car Mod : 1.0.17
- Ultimate Plane Mod : 1.1.2

**Other mods** (server-side)

[1.16.5]+SecurityCraft+v1.8.23.jar
1.16.5-additionalbars-2.0.3.jar
abnormals_core-1.16.5-3.2.0.jar
abnormals_delight-1.16.5-1.1.1.jar
advancedperipherals-0.6.7b.jar
allurement-1.16.5-1.2.0.jar
antiqueatlas-6.0.1-forge-mc1.16.5.jar
appleskin-forge-mc1.16.x-2.1.0.jar
Aquaculture-1.16.5-2.1.19.jar
architectury-1.20.28-forge.jar
astikorcarts-1.16.5-1.1.1.jar
atmospheric-1.16.5-3.1.0.jar
AutoRegLib-1.6-49.jar
autumnity-1.16.5-2.1.1.jar
bedspreads-forge-1.16.5-5.1.0.2.jar
BetterCaves-Forge-1.16.4-1.1.2.jar
BetterMineshafts-Forge-1.16.4-2.0.4.jar
bettermobgriefinggamerule-1.16.5-9.0.0.jar
BiomesOPlenty-1.16.5-13.1.0.481-universal.jar
blockcarpentry-1.16-0.3.6.jar
Botania-1.16.5-419.jar
BrandonsCore-1.16.5-3.0.8.232-universal.jar
buzzier_bees-1.16.5-3.0.1.jar
camera-1.16.5-1.0.14.jar
car-1.16.5-1.0.17.jar
carryon-1.16.5-1.15.5.15.jar
cc-tweaked-1.16.5-1.98.1.jar
cfm-7.0.0pre22-1.16.3.jar
cgm-1.0.1-1.16.3.jar
Chisel-MC1.16.5-2.0.1-alpha.4.jar
chunkloaders-1.1.7-mc1.16.5.jar
citadel-1.7.2-1.16.5.jar
cloth-config-4.11.26-forge.jar
Clumps-6.0.0.25.jar
CodeChickenLib-1.16.5-4.0.2.429-universal.jar
cofh_core-1.16.5-1.3.1.jar
collective-1.16.5-2.43.jar
Colony4ComputerCraft-1.16.5-1.3.0.jar
comforts-forge-1.16.5-4.0.1.1.jar
constructionwand-1.16.5-2.2.jar
Controlling-7.0.0.23.jar
CookingForBlockheads_1.16.5-9.3.3.jar
CosmeticArmorReworked-1.16.5-v4.jar
CraftableHorseArmour-1.16.5-1.6.jar
craftingstation-4.1.1.jar
CraftTweaker-1.16.5-7.1.0.357.jar
create-mc1.16.5_v0.3.2b.jar
CTM-MC1.16.1-1.1.2.6.jar
curios-forge-1.16.5-4.0.5.2.jar
DoggyTalents-1.16.5-2.0.1.10.jar
Draconic-Evolution-1.16.5-3.0.11.396-universal.jar
DungeonCrawl-1.16.3-2.2.4.jar
dungeons_plus-1.16.5-1.1.5.jar
DynamicSurroundings-1.16.4-4.0.4.2.jar
endergetic-1.16.4-3.0.0.jar
EnderStorage-1.16.5-2.8.0.168-universal.jar
engineersdecor-1.16.4-1.1.14.jar
environmental-1.16.5-1.0.0.jar
extraboats-1.16.5-2.1.0.jar
extremeSoundMuffler-3.13-1.16.5.jar
FarmersDelight-1.16.5-0.4.5.jar
FastLeafDecay-v25.jar
flourpower-1.16.x-1.2.0.jar
FluxNetworks-1.16.5-6.1.7.12.jar
flywheel-1.16-0.1.1.jar
FriendlyFire-1.16.5-7.0.4.jar
ftb-backups-2.1.1.6.jar
ftb-chunks-forge-1605.3.1-build.41.jar
ftb-library-forge-1605.3.1-build.58.jar
ftb-teams-forge-1605.2.1-build.20.jar
geckolib-forge-1.16.5-3.0.42.jar
globalxp-1.16.5-v1.8.jar
goblintraders-1.6.0-1.16.3.jar
gravestone-1.16.5-1.0.6.jar
ImmersiveEngineering-1.16.5-5.0.3-138.jar
ImmersivePetroleum-1.16.5-3.3.0-5.jar
industrial-foregoing-1.16.5-3.2.14.3-9.jar
invtweaks-1.16.4-1.0.1.jar
ironchest-1.16.5-11.2.13.jar
jei-1.16.5-7.7.1.110.jar
journeymap-1.16.5-5.7.3.jar
JustEnoughResources-1.16.5-0.12.1.121.jar
light-overlay-5.8.1.jar
mana-and-artifice-1.4.0.8.jar
Mantle-1.16.5-1.6.115.jar
mapperbase-1.16.5-2.4.0.0.jar
mcjtylib-1.16-5.0.21.jar
mcw-bridges-1.0.6-mc1.16.5.jar
mcw-doors-1.0.3-mc1.16.5.jar
mcw-fences-1.0.0-mc1.16.5.jar
mcw-furniture-2.0.1-mc1.16.5.jar
mcw-lights-1.0.0-mc1.16.5.jar
mcw-roofs-2.0.1-mc1.16.5-4.jar
mcw-trapdoors-1.0.2-mc1.16.5.jar
mcw-windows-1.0.3-mc1.16.5.jar
Mekanism-1.16.5-10.0.21.448.jar
MekanismAdditions-1.16.5-10.0.21.448.jar
MekanismGenerators-1.16.5-10.0.21.448.jar
MekanismTools-1.16.5-10.0.21.448.jar
minecolonies-0.14.342-BETA-universal.jar
MiniCoal2-1.16.1-0.0.2-universal.jar
morered_computercraft_integration-1.16.5-1.0.0.0.jar
morered-1.16.5-2.1.1.0.jar
Morpheus-1.16.5-4.2.70.jar
movingelevators-1.2.34-mc1.16.5.jar
mowziesmobs-1.5.19.jar
nametagtweaks_1.16.5-1.6.jar
NaturesCompass-1.16.5-1.9.1-forge.jar
NetherPortalFix_1.16.3-7.2.1.jar
obfuscate-0.6.2-1.16.3.jar
Patchouli-1.16.4-53.1.jar
personality-1.16.5-1.0.2.jar
pipez-1.16.5-1.2.8.jar
plane-1.16.5-1.1.2.jar
pneumaticcraft-repressurized-1.16.5-2.13.2-205.jar
polymorph-forge-1.16.5-0.25.jar
Psi+1.16-95.jar
QuarkOddities-1.16.3.jar
Quark-r2.4-316.jar
rats-7.2.0-1.16.5.jar
refinedstorage-1.9.15.jar
refinedstorageaddons-0.7.3.jar
repurposed_structures-1.16.5-2.7.12-forge.jar
restrictions-1.16-3.0.3.jar
rftoolsbase-1.16-2.0.11.jar
rftoolsbuilder-1.16-3.1.0.jar
rftoolscontrol-1.16-4.0.11.jar
rftoolsdim-1.16-7.0.11-beta.jar
rftoolspower-1.16-3.0.9.jar
rftoolsstorage-1.16-2.0.12.jar
rftoolsutility-1.16-3.1.0.jar
roadstuff-1.16.5-4.3.0.jar
rsgauges-1.16.4-1.2.11.jar
seeker_compass-1.16.5-3.0.0.jar
silent-gear-1.16.5-2.6.30.jar
silent-lib-1.16.3-4.9.6.jar
simplylight-1.16.4-1.1.3.jar
SpawnerFix-1.16.2-1.0.0.2.jar
StorageDrawers-1.16.3-8.3.0.jar
structure_gel-1.16.5-1.7.7.jar
structurize-0.13.208-ALPHA-universal.jar
supermartijn642configlib-1.0.9-mc1.16.jar
supermartijn642corelib-1.0.12-mc1.16.5.jar
TConstruct-1.16.5-3.1.0.231.jar
theoneprobe-1.16-3.1.4.jar
thermal_cultivation-1.16.5-1.3.0.jar
thermal_expansion-1.16.5-1.3.0.jar
thermal_foundation-1.16.5-1.3.1.jar
thermal_innovation-1.16.5-1.3.0.jar
thermal_locomotion-1.16.5-1.3.0.jar
titanium-1.16.5-3.2.8.4-10.jar
torchmaster-2.3.7.jar
u_team_core-1.16.5-3.2.1.196.jar
upgrade_aquatic-1.16.5-3.1.0.jar
useful_railroads-1.16.5-1.4.6.38.jar
valhelsia_core-16.0.9.jar
valhelsia_structures-1.16.5-0.1.4.jar
vehicle-mod-0.45.2-1.16.3.jar
Waystones_1.16.5-7.6.2.jar
xnet-1.16-3.0.13.jar
XNetGases-1.16.5-2.2.6.jar
YungsApi-1.16.4-Forge-11.jar

**Comment by henkelmax** [comment]
The plane does not go in your inventory. It always drops at the center point of the plane. This is not a bug.

**Comment by ExDomino** [comment]
It has not dropped at all, the plane just vanished !

**Comment by henkelmax** [comment]
Does this also happen without any other mods?
Please also provide your logs.
