### ISSUE TITLE
plane hitting "invisible" border and cause sudden drop in speed and altitude

### ISSUE THREAD

**Issue by ink717** [henkelmax/ultimate-plane-mod#18]
This was not found in any logs, but being a constant issue since 1 particular version earlier this year till now. When flying, sometimes the plane just feels like "hit" something in the air, and the speed/altitude drops, then catch back. No damage to the airplane. Is that due to any entity movement correction behavior? 

it happened to me in 1.16.5 mostly all forge versions, in server.

**Comment by henkelmax** [comment]
This happens when you are hitting unloaded chunks. Consider buying a more powerful server/computer.

**Comment by ink717** [comment]
this issue still exists.
we've updated to the most high-end hardware for the server and my PC and reduced the render distance down to 8. The issue still remains. None of the other rideable entities (vanilla/modded) have issues like that. We have scheduled player rail service running 160km/h consistently across various chunks with no issue. 

Maybe try looking into server tick compensation? We once had similar issues with another mod, which was resolved after turning that function off.

**Comment by ink717** [comment]
this issue still exists, in all versions. 
I tried the most powerful server and PC ever with all the newest gen hardware and it won't fix it. simply not this described problem.

**Comment by henkelmax** [comment]
Minecraft simply is not made for travelling that fast. Theres really nothing that can be done about that.

**Comment by ink717** [comment]
> Minecraft simply is not made for traveling that fast. There's really nothing that can be done about that.


I'm not intended to be nosey, I'd really like your constant contribution to the community and your hard work. However, as a responsible and contributing player and server, I'd like to point out that even when the plane was flying at really low airspeed, the air wall still happens. This issue doesn't happen in Ultimate car mod, or any other passenger-carrying entities mod that travels way over 200km/h and is codded much more complicated than this. 
If this is something that you need an extra hand to help with, I'm more than glad to work on it.
If you'd like to not keep the thing as it is, it's okay, and no pressure.

**Comment by henkelmax** [comment]
> If this is something that you need an extra hand to help with, I'm more than glad to work on it.

If you have coding experience I would appreciate if you would look into it.
I always appreciate PRs.

But all the time I had this issue, it was that the plane was in unloaded chunks.
