### ISSUE TITLE
Helicopters

### ISSUE THREAD

**Issue by LaBestiaBrutal** [henkelmax/ultimate-plane-mod#19]
**Is your feature request related to a problem? Please describe.**
The planes are awesome, flying feels great. But helicopters bring certain control over the air, planes do not have. So I was searching for another mod, there is not for 1.18.1 forge.

**Describe the solution you'd like**
A tier of helicopters would be just sick, imagine that. :)

**Describe alternatives you've considered**
A cargo chopper, and one built for more speed.

**Additional context**
It is just a thought I had, I know it is very hard to do mods like this, but it would just bring a sense of wholeness to Ultimate Planes.

Peace, sweet mod anyways!

**Comment by henkelmax** [comment]
Sorry, but I do not plan on adding Helicopters.
