### ISSUE TITLE
Crash the game by hitting a biological entity

### ISSUE THREAD

**Issue by xXN1ckWa1k3rXx** [henkelmax/ultimate-plane-mod#22]
**Please read the [FAQ](https://modrepo.de/minecraft/plane/faq) before submitting a bug report!**

**Bug description**
The game crashes when hitting some entity
Some mob entities do not crash the game but some entities are hit by planes and crash the game (eg: Squid and Enderman and slime)

**Steps to reproduce the issue**
1.Get a plane
2. Generate Enderman
3. fly and hit enderman
4. wait 1s
5. crash
(Now hit slime will crash too :V)

**Expected behavior**
Everytime hit enderman will game crash
3/11/2022: o yeah. hit slime will crash too

**Log files**
hit slime: https://gist.github.com/xXN1ckWa1k3rXx/c420f07cbd84c5ef94c2ec0bf09f035d

hit enderman:
https://gist.github.com/xXN1ckWa1k3rXx/a094287b49d6c3e062651b1ca51a1e20

**Versions**
- Minecraft version: 1.17.1
- Forge version: 37.1.1
- Mod version: car: 1.17.1-1.0.12; Plane: 1.17.1-1.0.2; OptiFine_1.17.1_U_H1

**Other mods**
only optifine
disbled optifine mod game crash too

**Screenshots (Optional)**
Screenshots of the issue.

**Comment by henkelmax** [comment]
There are no log files in the video. Please use GitHub Gist for logs.
Also please test if this happens without any other mods (e.g. OptiFine)

**Comment by xXN1ckWa1k3rXx** [comment]
Added bug template
Disabling optifine has now been tested. But the game still crashes
(Crash Entity added slime)
