### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by alazeprt** [henkelmax/ultimate-plane-mod#25]
Build failed information:
`Caused by: java.io.FileNotFoundException: D:\slatt-desktop\Java\ultimate-plane-mod\curseforge_api_key.txt `

**Bug description**
An error occurred when building after importing the project with idea

**Steps to reproduce the issue**
1. Open project with idea
2. Using idea to build gradlew project

**Comment by henkelmax** [comment]
You need `curseforge_api_key.txt`, `modrinth_token.txt` and `forge_update_key.txt` in the workspace folder.
