### ISSUE TITLE
custom recipes and fuel consumption on mod config 

### ISSUE THREAD

**Issue by fabriziogamboap** [henkelmax/ultimate-plane-mod#27]
**Is your feature request related to a problem? Please describe.**
It will be great to have the option to change the crafting recipes for the engine or plane wrench, because in older versions it was easier to craft them and also to change the fuel consumption of the plane, so you can travel longer distances, speccially on survival servers like mine.

**Describe the solution you'd like**
Add the option to choose which items will be used for the crafting, and the fuel consumption feature

**Describe alternatives you've considered**

**Additional context**

**Comment by henkelmax** [comment]
https://www.curseforge.com/minecraft/mc-mods/crafttweaker
