### ISSUE TITLE
crash during startup phase

### ISSUE THREAD

**Issue by ink717** [henkelmax/ultimate-plane-mod#28]
Minecraft 1.19.2 Forge 43.2.4

The crash happens in _roughly 10%_ chance during the start-up.

[crash-2023-02-24_23.49.57-fml.txt](https://github.com/henkelmax/ultimate-plane-mod/files/10830279/crash-2023-02-24_23.49.57-fml.txt)

**Comment by henkelmax** [comment]
Please fill out the bug template

**Comment by henkelmax** [comment]
Closed due to inactivity
