### ISSUE TITLE
Game Freezes when certain event occurs

### ISSUE THREAD

**Issue by CookerSmile** [henkelmax/ultimate-plane-mod#30]
Game will freeze when 
 [Server thread/WARN] [minecraft/SynchedEntityData]: defineId called for: class de.maxhenkel.plane.entity.EntityPlaneControlBase from class de.maxhenkel.plane.entity.EntityPlaneFuelBase
occurs in the output monitor

Specific part of my world that has planes and cars near gas stations as well as CreateMod objects and ChiselsBits blocks, But other part of world has same things but not game freeze.

**Expected behavior**
Go near location, code comes up in output monitor, game freezes (program not responding)

[debug.log](https://github.com/henkelmax/ultimate-plane-mod/files/11226605/debug.log)

**Versions**
- MC 1.18.2
- 40.2.1
- 1.0.0

Not sure if its a specific mod but I previously had an issue that prevented the game from starting though was fixed by reinstalling forge. I should also note that this does not happen in any other worlds with objects/entities mentioned
![image](https://user-images.githubusercontent.com/102698682/231885105-303a104d-2c6e-407d-84d8-9ab9114acf77.png)

**Comment by henkelmax** [comment]
I'm sorry, but I will only provide support for 1.19.2 and 1.19.4. I can't keep maintaining too many different Minecraft versions, as my time is pretty limited at the moment.

**Comment by CookerSmile** [comment]
fair enough
