### ISSUE TITLE
Plane Mini-GUI (in right left corner) covers the Sound Subtitles 

### ISSUE THREAD

**Issue by Aleksszz** [henkelmax/ultimate-plane-mod#33]
**Bug description**
The Plane Mini-GUI covers the Sound Subtitles GUI

**Steps to reproduce the issue**
1. Enable Subtitles under Sound settings
2. Enter Plane
3. See error

**Expected behavior**
Covers the Sound Subtitles.

**Versions**
- Minecraft version 1.20.1
- Forge version 47.2.0
- Mod version 1.0.6

**Comment by henkelmax** [comment]
There are no spots on the screen where nothing is shown. If you don't want the GUI, you can just disable it.
