### ISSUE TITLE
Rendering bug with bliss shaders

### ISSUE THREAD

**Issue by ink717** [henkelmax/ultimate-plane-mod#39]
### Bug description

In versions across 1.20 to 1.21.1, when using Bliss shaders with the car and plane mod, the entities will be rendered transparent. Tested on both Forge and NeoForge oculus/iris versions.

![2024-10-05_18 06 53](https://github.com/user-attachments/assets/ebfbb070-1f4b-4cbf-93e4-d66818fee435)
![2024-10-05_18 09 14](https://github.com/user-attachments/assets/275268df-cbdb-404f-b9dd-501099d7ac8a)

### Minecraft version

1.21.1

### Mod version

1.21.1-1.5.5

### Mod loader and version

NeoForge 21.1.65

### Steps to reproduce

1. Install mods
2. Turn on bliss shaders

### Expected behavior

Transparent textures

### Log files

https://paste.atlauncher.com/view/4a176f30-4c3a-4ffc-86bb-dd9ca2655b0b

### Screenshots

![2024-10-05_18 06 53](https://github.com/user-attachments/assets/c3e04672-4f9f-4d4d-b17a-1dbf6b282242)
![2024-10-05_18 09 14](https://github.com/user-attachments/assets/a9b19779-523d-46b7-9ced-f823fb741a9f)

**Comment by henkelmax** [comment]
Did this also happen in 1.0.x versions?

**Comment by ink717** [comment]
Yes it did. I just tested older versions on forge 1.19.2 and the same issue still persists.

I believe it’s more likely an issue around bliss shaders, but still worth looking into the cause.

Best

On Oct 6, 2024, at 3:42 AM, Max Henkel ***@***.***> wrote:

﻿

Did this also happen in 1.0.x versions?

**Comment by henkelmax** [comment]
Yeah theres not really much I can do about that issue then. Please report it to their issue tracker.
