### ISSUE TITLE
Bug: Additional square brackets in plane name

### ISSUE THREAD

**Issue by kolamp** [henkelmax/ultimate-plane-mod#5]
**Bug description**
When placing a plane inside the world, square brackets are added to the name, i.e. "Plane" becomes "[Plane]". The effect is recursive, when the plane is obtained by a plane wrench, ultimately leading to a game crash, when the name string becomes too long.

**Steps to reproduce the issue**
1. Obtain a plane in the inventory by any means - crafting, console command, plane wrench...
2. Place the plane inside the world by right-clicking.
3. Observed name change.

**Expected behavior**
The name of the plane should not change, when placing it.

**Log files**
https://paste.ee/p/M2XEo

**Versions**
- Minecraft 1.16.5
- Forge 36.1.0
- Mods car-1.0.4 & plane-1.0.2

**Other mods**
None.

**Screenshots (Optional)**
![2021-04-02_13 55 09](https://user-images.githubusercontent.com/44051049/113414031-4c68bf80-93bc-11eb-96da-0a98b4445cc0.png)
![2021-04-02_13 55 18](https://user-images.githubusercontent.com/44051049/113414049-58ed1800-93bc-11eb-877c-28567fe2e2f2.png)

**Comment by henkelmax** [comment]
Thank you for reporting this issue! It should be fixed in the next version.
