### ISSUE TITLE
My game crashes when flying

### ISSUE THREAD

**Issue by amandexspeed** [henkelmax/ultimate-plane-mod#6]
**Please read the [FAQ](https://modrepo.de/minecraft/plane/faq) before submitting a bug report!**

**Bug description**
I was flying when my game stopped and crashed with java.exception.nullpointer 

**Steps to reproduce the issue**
1. Fly

**Expected behavior**
My game doesn't crash

**Log files**
[latest.log](https://github.com/henkelmax/ultimate-plane-mod/files/6392050/latest.log)
[crash-2021-04-28_10.12.34-client.txt](https://github.com/henkelmax/ultimate-plane-mod/files/6392053/crash-2021-04-28_10.12.34-client.txt)

**Versions**
- Minecraft version 1.16.5
- Forge version 36.1.2
- Mod version 1.16.5 1.0.0

**Comment by henkelmax** [comment]
This seems to be an optifine issue. Please try if it happens without it. If it still crashes, let me know and I will reopen the issue. If not, you can report it to their issue tracker, but don't get your hopes too high, almost every mod has problems with optifine. I think fixing incompatibilities with mods isn't their highest priority.

**Comment by amandexspeed** [comment]
All your mods crashes with optifine. Why don't you try to make your mods compatible?
I like so much of your mods, but... I love my shaders too. 
If it keeps going like this unfortunally i'll stop using your mods.
I have 30+ mods and nothing crashes, but your mods crashes by the same thing.

**Comment by henkelmax** [comment]
There is no way I can find out what is causing the crashes, since OptiFine is closed source. And since it works without it, I'm assuming the fault is on their end.

**Comment by amandexspeed** [comment]
I'm a junior programmer and understood your situacion now, I know that the information i have( It crashes in the block alias) doesn't help soo much. I'll try to talk with optifine guys if they say something that can help

**Comment by henkelmax** [comment]
Yeah, it would be awesome to solve these incompatibility issues

**Comment by amandexspeed** [comment]
https://github.com/sp614x/optifine/issues/5601

Here's my optifine issue
