### ISSUE TITLE
cannot compile mod by ourselves ?

### ISSUE THREAD

**Issue by nouknouk** [henkelmax/ultimate-plane-mod#7]
Hi,

First, many thanks for this great work and for sharing it to the community 👍
I'm completely new to minecraft mod development, so please excuse me if my question is a dumb one.

I tried to clone the repo to make (& PR) some improvements (adding fuel consumption factor property ; goal is to be able to set it to `0` and let my young children use planes on my server without the need to create fuel).

I was unable to get a successfull compilation:

- first two API key files were missing (`curseforge_api_key.txt`, `forge_update_api_key.txt`) ; I suppose it's normal, as they look like secrets for curseforge mod signing (?) / publishing (?). I bypassed the 'issue' by creating fake files (with `0` in content)

- but I'm now blocked by an attempt to `gradlew build` because of the following issue: `Could not GET 'https://maven.tehnut.info/de/maxhenkel/corelib/corelib/1.16.5-1.0.4/corelib-1.16.5-1.0.4.pom'. Received status code 403 from server: Forbidden`

➡️ Is this forbidden access to `corelib` the expected behavior ? 

➡️ If so, does this means that the mod isn't compilate/modifiable/can be improved by third parties (like me) ?

Thanks in advance for your answers.
Best regards.

**Comment by henkelmax** [comment]
Sorry, I forgot to publish the latest version to maven.
Should work once the pipeline is finished:
https://github.com/henkelmax/corelib/runs/2589352847?check_suite_focus=true
